Repository wuyasan/Speaking-Portal-B, pull requests merged in 2022-10, with the labels that each got.

#11 Requirements doc drafts, Folder structure and README updates
  README.md
  docs/README.md
  docs/design-and-requirements/README.md
  docs/design-and-requirements/Use_Case_Diagram.png
  docs/design-and-requirements/project_requirements_and_design_draft.pdf
  docs/meeting-logs/README.md
  docs/meeting-logs/client/README.md
  docs/meeting-logs/team/README.md
  docs/research/README.md
Labels: documentation, Task, Chore

#13 Meeting notes team agreement
  Team Agreement.md
  docs/meeting-logs/client/meeting_notes_sept23rd.md
Labels: documentation, Task

#24 Sarvagyya - add research notes. Update all research file names
  docs/research/Cooper_Research.md
  docs/research/Sarvagya_Research.md
  docs/research/Wanli_Research.md
  docs/research/Yash_Research.md
Labels: Task, Exploration

#29 Research
  docs/meeting-logs/client/meeting_notes_oct_7th.md
Labels: documentation

#32 md files for requirements and design doc
  docs/design-and-requirements/design.md
  docs/design-and-requirements/requirements.md
  docs/design-and-requirements/use-case-diagram.png
Labels: documentation, Chore

#39 Updated requirements.md
  docs/design-and-requirements/dataflow_diagram.png
  docs/design-and-requirements/requirements.md
Labels: Task

#52 add script to start gentle container
  src/docker_script.py
Labels: Task

#53 script for getting alignment output from gentle
  data/audio/test.mp3
  data/text/test.txt
  requirements.txt
  src/docker_script.py
  src/gentle_out.py
Labels: Task
